#!/usr/bin/env bash

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
source "${ROOT_DIR}/e2e/lib/common.sh"
trap e2e::cleanup EXIT

e2e::prepare_test_env "install_and_init"
TEST_DIR="${JAIPH_E2E_TEST_DIR}"

e2e::section "Installer and smoke checks"

# When
help_output="$(jaiph --help)"

# Then
# assert_contains: help text includes dynamic command list and version info that vary across builds
e2e::assert_contains "${help_output}" "jaiph" "jaiph CLI responds to --help"

e2e::section "Project init and generated files"

# When
jaiph init "${TEST_DIR}"

# Then
if [[ -f "${TEST_DIR}/.jaiph/bootstrap.jh" ]]; then
  BOOTSTRAP_FILE="${TEST_DIR}/.jaiph/bootstrap.jh"
else
  e2e::fail "Expected .jaiph/bootstrap.jh to exist after init"
fi
e2e::assert_file_exists "${BOOTSTRAP_FILE}" "bootstrap file exists"
e2e::assert_file_executable "${BOOTSTRAP_FILE}" "bootstrap file is executable"
e2e::assert_file_exists "${TEST_DIR}/.jaiph/SKILL.md" "SKILL.md exists"

if ! cmp -s "${BOOTSTRAP_FILE}" <(cat <<'EOF'
#!/usr/bin/env jaiph

# Bootstraps Jaiph workflows for this repository.
workflow default() {
  const bootstrap_summary = prompt """
    You are bootstrapping Jaiph for this repository.
    First, read the Jaiph agent bootstrap guide at:
    .jaiph/SKILL.md
    Follow that guide and Jaiph language rules exactly.
    Perform these tasks in order:
    1) Analyze repository structure, languages, package manager, and build/test/lint commands.
    2) Detect existing contribution conventions (branching, commit style, CI checks).
    3) Review and update .jaiph/Dockerfile for this specific repository.
       - This file defines the Docker sandbox (runtimes, package managers, build tools).
       - Align it with how this project is actually built and tested.
    4) Create or update Jaiph workflows under .jaiph/ for safe feature implementation, including:
       - preflight checks (clean git state, branch guards when relevant)
       - implementation workflow
       - verification workflow (tests/lint/build)
    5) Keep workflows minimal, composable, and specific to this project.
    6) Print a short usage guide with exact jaiph run commands.
    7) End your response with:
       - WHAT CHANGED: files touched and key edits
       - WHY: tie each edit to repository structure, tests, or sandbox needs
  """
  log "Bootstrap summary (what changed and why):"
  log "${bootstrap_summary}"
}
EOF
); then
  e2e::fail "Expected .jaiph/bootstrap.jh to match init template with triple-quoted prompt"
fi
e2e::pass "bootstrap template matches expected triple-quoted prompt content"

jaiph compile "${BOOTSTRAP_FILE}"
e2e::pass "generated bootstrap workflow compiles"

e2e::assert_file_exists "${TEST_DIR}/.jaiph/Dockerfile" ".jaiph/Dockerfile exists"
expected_dockerfile="$(mktemp)"
cat > "${expected_dockerfile}" <<'EOF'
FROM ubuntu:latest

# Generated by jaiph init for project sandboxing.
# Keep this file aligned with your repository's runtime/build/test needs.

# Standard utilities + fuse-overlayfs for CoW sandbox
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
      bash \
      curl \
      git \
      ca-certificates \
      gnupg \
      fuse-overlayfs \
      fuse3 \
      rsync && \
    rm -rf /var/lib/apt/lists/*

# Node.js latest LTS (required by jaiph prompt stream helpers)
RUN curl -fsSL https://deb.nodesource.com/setup_lts.x | bash - && \
    apt-get install -y --no-install-recommends nodejs && \
    rm -rf /var/lib/apt/lists/*

# Non-root user keeps agent CLIs happy in Docker mode.
RUN useradd --create-home --uid 10001 --shell /bin/bash jaiph && \
    mkdir -p /jaiph/workspace /jaiph/workspace-ro /jaiph/run && \
    chown -R jaiph:jaiph /jaiph

# Claude Code CLI (Anthropic)
RUN npm install -g @anthropic-ai/claude-code

USER jaiph
ENV HOME=/home/jaiph
ENV PATH="/home/jaiph/.local/bin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

# cursor-agent (Cursor) — install as the runtime user so the binary remains
# reachable after switching away from root. The installer currently places
# the CLI in ~/.local/bin and may name it "agent" or "cursor".
RUN mkdir -p "$HOME/.local/bin" && \
    curl -fsSL https://cursor.com/install -o /tmp/install-cursor-agent.sh && \
    bash /tmp/install-cursor-agent.sh && \
    export PATH="$HOME/.local/bin:$PATH" && \
    if command -v cursor-agent >/dev/null 2>&1; then \
      true; \
    elif command -v agent >/dev/null 2>&1; then \
      ln -sf "$(command -v agent)" "$HOME/.local/bin/cursor-agent"; \
    elif command -v cursor >/dev/null 2>&1; then \
      ln -sf "$(command -v cursor)" "$HOME/.local/bin/cursor-agent"; \
    fi && \
    command -v cursor-agent >/dev/null 2>&1 && \
    rm -f /tmp/install-cursor-agent.sh

# jaiph (official installer: https://jaiph.org/install)
RUN curl -fsSL https://jaiph.org/install | bash

# Add project-specific package managers/build tools below as needed.

WORKDIR /jaiph/workspace
EOF
if ! cmp -s "${TEST_DIR}/.jaiph/Dockerfile" "${expected_dockerfile}"; then
  rm -f "${expected_dockerfile}"
  e2e::fail "Expected .jaiph/Dockerfile to match init template with jaiph.org installer"
fi
rm -f "${expected_dockerfile}"
e2e::pass ".jaiph/Dockerfile matches expected init template content"

# Bash command substitution strips a trailing newline; compare bytes with cmp.
if ! cmp -s "${TEST_DIR}/.jaiph/.gitignore" <(printf 'runs\ntmp\n'); then
  e2e::fail "Expected .jaiph/.gitignore to list runs and tmp with a final newline"
fi
e2e::pass ".jaiph/.gitignore lists runs and tmp"
