import { chmodSync, existsSync, mkdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { colorPalette } from "../shared/errors";
import { resolveInstalledSkillPath } from "../shared/paths";

const BOOTSTRAP_TEMPLATE = `#!/usr/bin/env jaiph

# Bootstraps Jaiph workflows for this repository.
workflow default() {
  const bootstrap_summary = prompt """
    You are bootstrapping Jaiph for this repository.
    First, read the Jaiph agent bootstrap guide at:
    .jaiph/SKILL.md
    Follow that guide and Jaiph language rules exactly.
    Perform these tasks in order:
    1) Analyze repository structure, languages, package manager, and build/test/lint commands.
    2) Detect existing contribution conventions (branching, commit style, CI checks).
    3) Review and update .jaiph/Dockerfile for this specific repository.
       - This file defines the Docker sandbox (runtimes, package managers, build tools).
       - Align it with how this project is actually built and tested.
    4) Create or update Jaiph workflows under .jaiph/ for safe feature implementation, including:
       - preflight checks (clean git state, branch guards when relevant)
       - implementation workflow
       - verification workflow (tests/lint/build)
    5) Keep workflows minimal, composable, and specific to this project.
    6) Print a short usage guide with exact jaiph run commands.
    7) End your response with:
       - WHAT CHANGED: files touched and key edits
       - WHY: tie each edit to repository structure, tests, or sandbox needs
  """
  log "Bootstrap summary (what changed and why):"
  log "\${bootstrap_summary}"
}
`;

/** Ignores ephemeral dirs under `.jaiph/`; kept in-repo so workflows and libs stay tracked. */
const JAIPH_DIR_GITIGNORE_TEMPLATE = "runs\ntmp\n";
const DOCKERFILE_TEMPLATE_MARKER = "# Generated by jaiph init for project sandboxing.";
const JAIPH_INSTALL_COMMAND = "curl -fsSL https://jaiph.org/install | bash";
const JAIPH_DOCKERFILE_TEMPLATE = `FROM ubuntu:latest

${DOCKERFILE_TEMPLATE_MARKER}
# Keep this file aligned with your repository's runtime/build/test needs.

# Standard utilities
RUN apt-get update && \\
    apt-get install -y --no-install-recommends \\
      bash \\
      curl \\
      git \\
      ca-certificates \\
      gnupg && \\
    rm -rf /var/lib/apt/lists/*

# Node.js latest LTS (required by jaiph prompt stream helpers)
RUN curl -fsSL https://deb.nodesource.com/setup_lts.x | bash - && \\
    apt-get install -y --no-install-recommends nodejs && \\
    rm -rf /var/lib/apt/lists/*

# Non-root user keeps agent CLIs happy in Docker mode.
RUN useradd --create-home --uid 10001 --shell /bin/bash jaiph && \\
    mkdir -p /jaiph/workspace && \\
    chown -R jaiph:jaiph /jaiph

# Claude Code CLI (Anthropic)
RUN npm install -g @anthropic-ai/claude-code

# cursor-agent (Cursor)
RUN curl -fsSL https://cursor.com/install -o /tmp/install-cursor-agent.sh && \\
    bash /tmp/install-cursor-agent.sh && \\
    export PATH="$HOME/.local/bin:$PATH" && \\
    if command -v cursor-agent >/dev/null 2>&1; then \\
      ln -sf "$(command -v cursor-agent)" /usr/local/bin/cursor-agent; \\
    elif command -v agent >/dev/null 2>&1; then \\
      ln -sf "$(command -v agent)" /usr/local/bin/cursor-agent; \\
    elif command -v cursor >/dev/null 2>&1; then \\
      ln -sf "$(command -v cursor)" /usr/local/bin/cursor-agent; \\
    fi && \\
    command -v cursor-agent >/dev/null 2>&1 && \\
    rm -f /tmp/install-cursor-agent.sh

USER jaiph
ENV HOME=/home/jaiph
ENV PATH="/home/jaiph/.local/bin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

# jaiph (official installer: https://jaiph.org/install)
RUN ${JAIPH_INSTALL_COMMAND}

# Add project-specific package managers/build tools below as needed.

WORKDIR /jaiph/workspace
`;

export function runInit(rest: string[]): number {
  const workspaceArg = rest[0] ?? ".";
  const workspaceRoot = resolve(workspaceArg);
  const stats = statSync(workspaceRoot);
  if (!stats.isDirectory()) {
    process.stderr.write(`jaiph init expects a directory path, got: ${workspaceArg}\n`);
    return 1;
  }

  const jaiphDir = join(workspaceRoot, ".jaiph");
  const gitignorePath = join(jaiphDir, ".gitignore");
  const bootstrapPath = join(jaiphDir, "bootstrap.jh");
  const dockerfilePath = join(jaiphDir, "Dockerfile");
  const skillPath = join(jaiphDir, "SKILL.md");
  const palette = colorPalette();

  process.stdout.write("\n");
  process.stdout.write("Jaiph init\n");
  process.stdout.write("\n");
  mkdirSync(jaiphDir, { recursive: true });

  let createdGitignore = false;
  if (existsSync(gitignorePath)) {
    const existingGitignore = readFileSync(gitignorePath, "utf8");
    if (existingGitignore !== JAIPH_DIR_GITIGNORE_TEMPLATE) {
      process.stderr.write(
        `jaiph init: ${join(".jaiph", ".gitignore")} exists with unexpected content; refusing to overwrite. Remove or replace it, then run again.\n`,
      );
      return 1;
    }
  } else {
    writeFileSync(gitignorePath, JAIPH_DIR_GITIGNORE_TEMPLATE, "utf8");
    createdGitignore = true;
  }

  let createdBootstrap = false;
  if (existsSync(bootstrapPath)) {
    if (readFileSync(bootstrapPath, "utf8") !== BOOTSTRAP_TEMPLATE) {
      process.stderr.write(
        `jaiph init: ${join(".jaiph", "bootstrap.jh")} exists with unexpected content; refusing to overwrite. Remove or replace it, then run again.\n`,
      );
      return 1;
    }
  } else {
    process.stdout.write(`${palette.dim}▸ Creating ${join(".jaiph", "bootstrap.jh")} in ${workspaceRoot}...${palette.reset}\n`);
    writeFileSync(bootstrapPath, BOOTSTRAP_TEMPLATE, "utf8");
    createdBootstrap = true;
  }
  chmodSync(bootstrapPath, 0o755);

  let createdDockerfile = false;
  let updatedDockerfile = false;
  let leftDockerfileUnchanged = false;
  if (existsSync(dockerfilePath)) {
    const existingDockerfile = readFileSync(dockerfilePath, "utf8");
    if (existingDockerfile === JAIPH_DOCKERFILE_TEMPLATE) {
      leftDockerfileUnchanged = true;
    } else if (existingDockerfile.includes(DOCKERFILE_TEMPLATE_MARKER)) {
      writeFileSync(dockerfilePath, JAIPH_DOCKERFILE_TEMPLATE, "utf8");
      updatedDockerfile = true;
    } else {
      leftDockerfileUnchanged = true;
    }
  } else {
    process.stdout.write(`${palette.dim}▸ Creating ${join(".jaiph", "Dockerfile")} in ${workspaceRoot}...${palette.reset}\n`);
    writeFileSync(dockerfilePath, JAIPH_DOCKERFILE_TEMPLATE, "utf8");
    createdDockerfile = true;
  }

  const installedSkillPath = resolveInstalledSkillPath();
  let wroteSkill = false;
  if (installedSkillPath) {
    writeFileSync(skillPath, readFileSync(installedSkillPath, "utf8"), "utf8");
    wroteSkill = true;
  }

  process.stdout.write(`${palette.green}✓ Initialized ${join(".jaiph", "bootstrap.jh")}${palette.reset}\n`);
  if (createdGitignore) {
    process.stdout.write(`${palette.green}✓ Created ${join(".jaiph", ".gitignore")}${palette.reset}\n`);
  } else {
    process.stdout.write(
      `${palette.dim}▸ Note: ${join(".jaiph", ".gitignore")} already matched the template; left unchanged.${palette.reset}\n`,
    );
  }
  if (!createdBootstrap) {
    process.stdout.write(`${palette.dim}▸ Note: bootstrap file already existed; left unchanged.${palette.reset}\n`);
  }
  if (createdDockerfile) {
    process.stdout.write(`${palette.green}✓ Created ${join(".jaiph", "Dockerfile")} with Jaiph installer${palette.reset}\n`);
  } else if (updatedDockerfile) {
    process.stdout.write(`${palette.green}✓ Updated ${join(".jaiph", "Dockerfile")} with latest init template${palette.reset}\n`);
  } else if (leftDockerfileUnchanged) {
    process.stdout.write(
      `${palette.dim}▸ Note: ${join(".jaiph", "Dockerfile")} already existed; left unchanged. Bootstrap workflow should review it for project sandbox needs.${palette.reset}\n`,
    );
  }
  if (wroteSkill) {
    process.stdout.write(`${palette.green}✓ Wrote ${join(".jaiph", "SKILL.md")} from installation${palette.reset}\n`);
  } else {
    process.stdout.write(
      `${palette.dim}▸ Note: skill file not found in installation (${join(".jaiph", "SKILL.md")} not written). Set JAIPH_SKILL_PATH and run again.${palette.reset}\n`,
    );
  }
  process.stdout.write("\n");
  process.stdout.write("Try:\n");
  process.stdout.write("  ./.jaiph/bootstrap.jh\n");
  process.stdout.write("\n");
  process.stdout.write("This asks an agent to analyze the project and scaffold recommended workflows.\n");
  process.stdout.write(
    "Ephemeral paths (`.jaiph/runs/`, `.jaiph/tmp/`) are ignored via `.jaiph/.gitignore`; commit workflows and the rest of `.jaiph/` as usual.\n",
  );
  process.stdout.write("\n");
  return 0;
}
