#!/usr/bin/env node
// Regenerates src/runtime/embedded-assets.ts from on-disk asset files so the
// `jaiph` binary stays self-contained (no sibling files needed at runtime).
//
// Run automatically as the first step of `npm run build`. The generated file
// is checked into git so a fresh checkout type-checks before the first build;
// a runtime test asserts the encoded contents match the current sources, so a
// stale checked-in copy fails CI rather than silently shipping outdated text.

const { readFileSync, writeFileSync } = require("node:fs");
const { join, resolve } = require("node:path");

const ROOT = resolve(__dirname, "..");

const ASSETS = [
  { name: "OVERLAY_RUN_SH", path: "runtime/overlay-run.sh" },
  { name: "JAIPH_SKILL_MD", path: "docs/jaiph-skill.md" },
];

const entries = ASSETS.map((asset) => {
  const bytes = readFileSync(join(ROOT, asset.path));
  return { ...asset, base64: bytes.toString("base64") };
});

const lines = [
  "// AUTO-GENERATED by tools/embed-assets.js — do not edit by hand.",
  "// Regenerated by `npm run build`. Sources:",
  ...ASSETS.map((a) => `//   - ${a.path}`),
  "//",
  "// Base64-encoded so a bun --compile binary carries the bytes inside the",
  "// executable; the embedded-assets test fails if these drift from disk.",
  "",
];

for (const entry of entries) {
  lines.push(`export const ${entry.name}_BASE64 =`);
  lines.push(`  ${JSON.stringify(entry.base64)};`);
  lines.push("");
}

lines.push(
  "export function decodeEmbeddedAsset(base64: string): string {",
  "  return Buffer.from(base64, \"base64\").toString(\"utf8\");",
  "}",
  "",
);

writeFileSync(join(ROOT, "src/runtime/embedded-assets.ts"), lines.join("\n"));
